name: Lint

on:
    schedule:
    -   cron: 00 00 * * 1  # run every Monday at 00:00
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'

        -   name: Cache pre-commit
            uses: actions/cache@v3
            with:
                path: ~/.cache/pre-commit
                key: pre-commit-${{ env.pythonLocation }}-${{ hashFiles('**/.pre-commit-config.yaml') }}

        -   name: Install dependencies
            run: |
                sudo apt-get update -y
                sudo apt install libenchant-2-dev pandoc
                python -m pip install --upgrade pip
                python -m pip install tox

        -   name: Linting
            run: |
                tox -e lint,check-docs,readme
